/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

/**
 *
 * @author pedro
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jInternalFramebemvindo = new javax.swing.JInternalFrame();
        jPanelintenalframe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtoncadalunos = new javax.swing.JButton();
        jButtoncadprofessores = new javax.swing.JButton();
        jButtoncadcordenadores = new javax.swing.JButton();
        jLabelagenda = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelfundotelaprincincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenucadastros = new javax.swing.JMenu();
        jMenuItemMedicos = new javax.swing.JMenuItem();
        jMenuprofessores = new javax.swing.JMenuItem();
        jMenucordenador = new javax.swing.JMenuItem();
        jMenuusuario = new javax.swing.JMenuItem();
        jMenurelatorio = new javax.swing.JMenu();
        jMenubemvindo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenusair = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFramebemvindo.setBorder(null);
        jInternalFramebemvindo.setTitle("Bem-Vindo");
        jInternalFramebemvindo.setVisible(true);
        jInternalFramebemvindo.getContentPane().setLayout(null);

        jPanelintenalframe.setLayout(null);

        jLabel2.setText("Cadastros -");
        jPanelintenalframe.add(jLabel2);
        jLabel2.setBounds(10, 10, 80, 14);

        jButtoncadalunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aluno.png"))); // NOI18N
        jButtoncadalunos.setToolTipText("Alunos");
        jButtoncadalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadalunosActionPerformed(evt);
            }
        });
        jPanelintenalframe.add(jButtoncadalunos);
        jButtoncadalunos.setBounds(10, 40, 70, 70);

        jButtoncadprofessores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/download.png"))); // NOI18N
        jButtoncadprofessores.setToolTipText("Professores");
        jPanelintenalframe.add(jButtoncadprofessores);
        jButtoncadprofessores.setBounds(80, 40, 85, 70);

        jButtoncadcordenadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/25ea3335.png"))); // NOI18N
        jButtoncadcordenadores.setToolTipText("Cordenadores");
        jPanelintenalframe.add(jButtoncadcordenadores);
        jButtoncadcordenadores.setBounds(160, 40, 85, 70);

        jLabelagenda.setText("Agenda -");
        jPanelintenalframe.add(jLabelagenda);
        jLabelagenda.setBounds(20, 140, 70, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Agenda.png"))); // NOI18N
        jButton1.setToolTipText("Agenda");
        jPanelintenalframe.add(jButton1);
        jButton1.setBounds(10, 170, 150, 110);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exit.png"))); // NOI18N
        jButton2.setToolTipText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelintenalframe.add(jButton2);
        jButton2.setBounds(820, 0, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/internalframe.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanelintenalframe.add(jLabel3);
        jLabel3.setBounds(0, -30, 860, 460);

        jInternalFramebemvindo.getContentPane().add(jPanelintenalframe);
        jPanelintenalframe.setBounds(0, 30, 860, 430);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFramebemvindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 270, 22);

        getContentPane().add(jInternalFramebemvindo);
        jInternalFramebemvindo.setBounds(0, 0, 860, 490);

        jLabelfundotelaprincincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/20b066b7012d029912313b075c91.jpeg"))); // NOI18N
        getContentPane().add(jLabelfundotelaprincincipal);
        jLabelfundotelaprincincipal.setBounds(0, 0, 860, 380);

        jMenucadastros.setText("Cadastros");

        jMenuItemMedicos.setText("Alunos");
        jMenucadastros.add(jMenuItemMedicos);

        jMenuprofessores.setText("Professores");
        jMenuprofessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuprofessoresActionPerformed(evt);
            }
        });
        jMenucadastros.add(jMenuprofessores);

        jMenucordenador.setText("Cordenadores");
        jMenucadastros.add(jMenucordenador);

        jMenuusuario.setText("Usuários");
        jMenucadastros.add(jMenuusuario);

        jMenuBar1.add(jMenucadastros);

        jMenurelatorio.setText("Relátorios");
        jMenuBar1.add(jMenurelatorio);

        jMenubemvindo.setText("Ferramentas");

        jMenuItem2.setText("Tela Bem-Vindo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenubemvindo.add(jMenuItem2);

        jMenuBar1.add(jMenubemvindo);

        jMenusair.setText("Sair");

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenusair.add(jMenuSair);

        jMenuBar1.add(jMenusair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(872, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuprofessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuprofessoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuprofessoresActionPerformed

    private void jButtoncadalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadalunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncadalunosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jInternalFramebemvindo.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
TelaPrincipal tela = new TelaPrincipal();
tela.setVisible(true);
dispose();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtoncadalunos;
    private javax.swing.JButton jButtoncadcordenadores;
    private javax.swing.JButton jButtoncadprofessores;
    private javax.swing.JInternalFrame jInternalFramebemvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelagenda;
    private javax.swing.JLabel jLabelfundotelaprincincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemMedicos;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jMenubemvindo;
    private javax.swing.JMenu jMenucadastros;
    private javax.swing.JMenuItem jMenucordenador;
    private javax.swing.JMenuItem jMenuprofessores;
    private javax.swing.JMenu jMenurelatorio;
    private javax.swing.JMenu jMenusair;
    private javax.swing.JMenuItem jMenuusuario;
    private javax.swing.JPanel jPanelintenalframe;
    // End of variables declaration//GEN-END:variables
}
